// Authentication
// export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_ERROR = 'REGISTER_ERROR'
// export const LOGIN_USER = 'LOGIN_ERROR';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_ERROR = 'LOGIN_ERROR';
// export const REDIRECTED = 'REDIRECTED';
// export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CHANGE_IS_AUTHENTICATED = 'CHANGE_IS_AUTHENTICATED';
export const SAVE_LOGGEDIN_USER_DATA = 'SAVE_LOGGEDIN_USER_DATA';
export const AUTH_RESET_STATE = 'RESET_STATE';
export const FETCH_LOGGEDIN_USER = 'FETCH_LOGGEDIN_USER';
export const FETCH_TIMELINE_USER = 'FETCH_TIMELINE_USER';
export const UPDATE_TIMELINE_USER = 'UPDATE_TIMELINE_USER';
export const UPDATE_USER_IMAGE_CLASS = 'UPDATE_USER_IMAGE_CLASS';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';

