// Authentication
export const CHANGE_IS_AUTHENTICATED = 'CHANGE_IS_AUTHENTICATED';
export const SAVE_LOGGEDIN_USER_DATA = 'SAVE_LOGGEDIN_USER_DATA';
export const AUTH_RESET_STATE = 'RESET_STATE';
export const FETCH_LOGGEDIN_USER = 'FETCH_LOGGEDIN_USER';
export const FETCH_TIMELINE_USER = 'FETCH_TIMELINE_USER';
export const UPDATE_TIMELINE_USER = 'UPDATE_TIMELINE_USER';
export const UPDATE_USER_IMAGE_CLASS = 'UPDATE_USER_IMAGE_CLASS';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';

