export const RESET_STATE = 'RESET_STATE';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const RESET_COMMENT_STATE = 'RESET_COMMENT_STATE';
export const FETCH_LAST_COMMENT_SUCCESS = 'FETCH_LAST_COMMENT_SUCCESS';
export const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS';
export const UPDATE_COMMENT_CREATOR_IMAGE_CLASS = 'UPDATE_COMMENT_CREATOR_IMAGE_CLASS';


