export const RESET_STATE = 'RESET_STATE';

export const POST_CREATE_BEGIN = 'POST_CREATE_BEGIN';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';

export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const LOADING_USER_POSTS = 'LOADING_USER_POSTS';
export const RESET_USER_POSTS_STATE = 'RESET_USER_POSTS_STATE';

export const FETCH_ALL_FOREIGN_POSTS = 'FETCH_ALL_FOREIGN_POSTS';
export const LOADING_FOREIGN_POSTS = 'LOADING_FOREIGN_POSTS';
export const RESET_FOREIGN_POSTS_STATE = 'RESET_FOREIGN_POSTS_STATE';

export const FETCH_FOLLOWING_POSTS = 'FETCH_FOLLOWING_POSTS';
export const LOADING_FOLLOWING_POSTS = 'LOADING_FOLLOWING_POSTS';
export const RESET_FOLLOWING_POSTS_STATE = 'RESET_FOLLOWING_POSTS_STATE';

export const UPDATE_POSTIMAGE_CLASS = 'UPDATE_POSTIMAGE_CLASS';
export const UPDATE_CREATOR_IMAGE_CLASS = 'UPDATE_CREATOR_IMAGE_CLASS';

export const CHANGE_POST_LIKE_SUCCESS = 'CHANGE_POST_LIKE_SUCCESS';

export const RESET_POST_STATE = 'RESET_POST_STATE';


