export const RESET_STATE = 'RESET_STATE';

export const POST_CREATE_BEGIN = 'POST_CREATE_BEGIN';

export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';

export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';

export const FETCH_ALL_FOREIGN_POSTS = 'FETCH_ALL_FOREIGN_POSTS';

export const UPDATE_POSTIMAGE_CLASS = 'UPDATE_POSTIMAGE_CLASS';
