// User
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_ADMIN = 'FETCH_ALL_USERS_ADMIN';
export const PROMOTE_USER = 'PROMOTE_USER';
export const DEMOTE_USER = 'DEMOTE_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';

export const RESET_STATE = 'RESET_STATE';
