// User
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_ADMIN = 'FETCH_ALL_USERS_ADMIN';
export const PROMOTE_USER = 'PROMOTE_USER';
export const DEMOTE_USER = 'DEMOTE_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const FETCH_ALL_FOLLOWERS = 'FETCH_ALL_FOLLOWERS';
export const FETCH_ALL_FOLLOWING = 'FETCH_ALL_FOLLOWING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const UPDATE_USER_IMAGE_CLASS = 'UPDATE_USER_IMAGE_CLASS';


export const RESET_STATE = 'RESET_STATE';
